name: Release Maven artifact and image
on:
  workflow_dispatch

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    environment: maven-workflow

    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: 'write'
      contents: 'write'
      packages: 'write'
      actions: 'read'

    steps:
      - name: Auth ECR
        id: ecr-auth
        uses: portx-phim/shared-actions/ecr-auth@main
        with:
          aws-account: '549231858676'

      - name: Generate token
        uses: navikt/github-app-token-generator@v1
        id: get-token
        with:
          private-key: ${{ secrets.WORKFLOWS_TOKEN_GEN_PRIVATE_KEY }}
          app-id: ${{ secrets.WORKFLOWS_TOKEN_GEN_APP_ID }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0
          token: ${{ steps.get-token.outputs.token }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '21'

      - name: Create Maven settings
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{"id":"github","url":"https://portx.jfrog.io/portx/portx-releases","releases":{"enabled":true},"snapshots":{"enabled":true}},{"id":"portx-repository-snapshots","url":"https://portx.jfrog.io/portx/portx-snapshots","releases":{"enabled":false},"snapshots":{"enabled":true}},{"id":"portx-repository-releases","url":"https://portx.jfrog.io/portx/portx-releases","releases":{"enabled":true},"snapshots":{"enabled":false}},{"id":"terracotta-snapshots","url":"https://www.terracotta.org/download/reflector/snapshots","releases":{"enabled":false},"snapshots":{"enabled":true}},{"id":"terracotta-releases","url":"https://www.terracotta.org/download/reflector/releases","releases":{"enabled":true},"snapshots":{"enabled":false}}]'
          servers: |
            [{"id": "portx-repository-snapshots", "username": "deployer", "password": "${{ secrets.PORTX_SNAPSHOTS_PASSWORD }}"},{"id": "portx-repository-releases", "username": "deployer", "password": "${{ secrets.PORTX_RELEASES_PASSWORD }}"}]
          output_file: settings.xml

      - name: Extract Git author info from token #This configures git from the token info - the token should be the global PAT configured per org
        id: git-author
        uses: release-plz/git-config@v0.1.2
        env:
          GITHUB_TOKEN: ${{ steps.get-token.outputs.token }}

      - name: Git config
        run: |
          echo "Git configured as follows:"
          echo "${{ steps.git-author.outputs.email }}"
          echo "${{ steps.git-author.outputs.name }}"
          git config user.name ${{ steps.git-author.outputs.name }}
          git config user.email ${{ steps.git-author.outputs.email }}

      - name: Start release
        run: mvn -B clean test gitflow:release-start -DgitFlowConfig.developmentBranch=main -Pnative -s settings.xml

      - name: Extract maven version (if present)
        id: maven_version
        if: ${{ hashFiles('pom.xml') != '' }}
        uses: mikefarah/yq@master
        with:
          cmd: yq '.project.version' pom.xml -r

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64
          provenance: false
          tags: ${{ steps.ecr-auth.outputs.images-repo-url }}/${{ github.event.repository.name }}:${{ steps.maven_version.outputs.result }}

      - name: Finish release
        run: mvn -B gitflow:release-finish -DskipReleaseMergeProdBranch=true -DgitFlowConfig.productionBranch=main -DgitFlowConfig.developmentBranch=dev -DkeepBranch=true -DreleaseMergeNoFF=false -Pnative -s settings.xml



